`timescale 1ns / 1ps

// Testbench for the complete CNN pipeline (cnn_fsm), with the input, convolution weight and FC
// weight memories modeled here with one cycle of read latency. Ten runs of three images (images
// 0-29 of reference/mnist_cnn.npz) use the course's trained weights, and every prediction is
// checked against the RTL-exact golden model (tools/cnn_reference.py). After the first run the 16
// Conv2 result memories are also compared with the model's Conv2 output, so a feature-map pixel
// stored in the wrong place fails even if the predicted digits survive it.
//
// Stimulus and expected results come from vectors/, generated by tools/gen_vectors.py. VECTOR_DIR
// is resolved against the simulator's working directory; tools/run_sims.py copies vectors/ there.
// Override it with -d VECTOR_DIR=<path> if needed.
`ifndef VECTOR_DIR
  `define VECTOR_DIR "vectors"
`endif

module tb_cnn_fsm;

    localparam INPUT_AMAX  = 2352;
    localparam CONV_AMAX   = 1224;
    localparam FC_AMAX     = 2304;
    localparam NUM_RUNS    = 10;
    localparam CONV2_WORDS = 16 * 576;

    reg clk    = 1'b0;
    reg resetn = 1'b0;
    reg start  = 1'b0;

    always #5 clk = ~clk;

    wire       done;
    wire [3:0] result_0, result_1, result_2;

    wire        input_en, input_we;
    wire [11:0] input_addr;
    reg  [7:0]  input_dout;

    wire        conv_en, conv_we;
    wire [10:0] conv_addr;
    reg  [7:0]  conv_dout;

    wire        fcl_en_0, fcl_en_1, fcl_en_2, fcl_en_3, fcl_en_4;
    wire        fcl_en_5, fcl_en_6, fcl_en_7, fcl_en_8, fcl_en_9;
    wire        fcl_we_0, fcl_we_1, fcl_we_2, fcl_we_3, fcl_we_4;
    wire        fcl_we_5, fcl_we_6, fcl_we_7, fcl_we_8, fcl_we_9;
    wire [11:0] fcl_addr_0, fcl_addr_1, fcl_addr_2, fcl_addr_3, fcl_addr_4;
    wire [11:0] fcl_addr_5, fcl_addr_6, fcl_addr_7, fcl_addr_8, fcl_addr_9;
    reg  [7:0]  fcl_dout_0, fcl_dout_1, fcl_dout_2, fcl_dout_3, fcl_dout_4;
    reg  [7:0]  fcl_dout_5, fcl_dout_6, fcl_dout_7, fcl_dout_8, fcl_dout_9;

    cnn_fsm dut (
        .clk(clk),
        .resetn(resetn),
        .start(start),
        .done(done),
        .result_0(result_0),
        .result_1(result_1),
        .result_2(result_2),

        .input_en(input_en),
        .input_we(input_we),
        .input_addr(input_addr),
        .input_dout(input_dout),

        .conv_en(conv_en),
        .conv_we(conv_we),
        .conv_addr(conv_addr),
        .conv_dout(conv_dout),

        .fcl_en_0(fcl_en_0), .fcl_we_0(fcl_we_0), .fcl_addr_0(fcl_addr_0), .fcl_dout_0(fcl_dout_0),
        .fcl_en_1(fcl_en_1), .fcl_we_1(fcl_we_1), .fcl_addr_1(fcl_addr_1), .fcl_dout_1(fcl_dout_1),
        .fcl_en_2(fcl_en_2), .fcl_we_2(fcl_we_2), .fcl_addr_2(fcl_addr_2), .fcl_dout_2(fcl_dout_2),
        .fcl_en_3(fcl_en_3), .fcl_we_3(fcl_we_3), .fcl_addr_3(fcl_addr_3), .fcl_dout_3(fcl_dout_3),
        .fcl_en_4(fcl_en_4), .fcl_we_4(fcl_we_4), .fcl_addr_4(fcl_addr_4), .fcl_dout_4(fcl_dout_4),
        .fcl_en_5(fcl_en_5), .fcl_we_5(fcl_we_5), .fcl_addr_5(fcl_addr_5), .fcl_dout_5(fcl_dout_5),
        .fcl_en_6(fcl_en_6), .fcl_we_6(fcl_we_6), .fcl_addr_6(fcl_addr_6), .fcl_dout_6(fcl_dout_6),
        .fcl_en_7(fcl_en_7), .fcl_we_7(fcl_we_7), .fcl_addr_7(fcl_addr_7), .fcl_dout_7(fcl_dout_7),
        .fcl_en_8(fcl_en_8), .fcl_we_8(fcl_we_8), .fcl_addr_8(fcl_addr_8), .fcl_dout_8(fcl_dout_8),
        .fcl_en_9(fcl_en_9), .fcl_we_9(fcl_we_9), .fcl_addr_9(fcl_addr_9), .fcl_dout_9(fcl_dout_9)
    );

    // memories, read with one cycle of latency
    reg [7:0] input_mem [0:INPUT_AMAX-1];
    reg [7:0] conv_mem  [0:CONV_AMAX-1];
    reg [7:0] fc_mem_0  [0:FC_AMAX-1];
    reg [7:0] fc_mem_1  [0:FC_AMAX-1];
    reg [7:0] fc_mem_2  [0:FC_AMAX-1];
    reg [7:0] fc_mem_3  [0:FC_AMAX-1];
    reg [7:0] fc_mem_4  [0:FC_AMAX-1];
    reg [7:0] fc_mem_5  [0:FC_AMAX-1];
    reg [7:0] fc_mem_6  [0:FC_AMAX-1];
    reg [7:0] fc_mem_7  [0:FC_AMAX-1];
    reg [7:0] fc_mem_8  [0:FC_AMAX-1];
    reg [7:0] fc_mem_9  [0:FC_AMAX-1];

    always @(posedge clk) begin
        if (input_en)
            input_dout <= input_mem[input_addr];
        if (conv_en)
            conv_dout <= conv_mem[conv_addr];
        if (fcl_en_0 && !fcl_we_0) fcl_dout_0 <= fc_mem_0[fcl_addr_0];
        if (fcl_en_1 && !fcl_we_1) fcl_dout_1 <= fc_mem_1[fcl_addr_1];
        if (fcl_en_2 && !fcl_we_2) fcl_dout_2 <= fc_mem_2[fcl_addr_2];
        if (fcl_en_3 && !fcl_we_3) fcl_dout_3 <= fc_mem_3[fcl_addr_3];
        if (fcl_en_4 && !fcl_we_4) fcl_dout_4 <= fc_mem_4[fcl_addr_4];
        if (fcl_en_5 && !fcl_we_5) fcl_dout_5 <= fc_mem_5[fcl_addr_5];
        if (fcl_en_6 && !fcl_we_6) fcl_dout_6 <= fc_mem_6[fcl_addr_6];
        if (fcl_en_7 && !fcl_we_7) fcl_dout_7 <= fc_mem_7[fcl_addr_7];
        if (fcl_en_8 && !fcl_we_8) fcl_dout_8 <= fc_mem_8[fcl_addr_8];
        if (fcl_en_9 && !fcl_we_9) fcl_dout_9 <= fc_mem_9[fcl_addr_9];
    end

    reg [3:0]       expected       [0:3*NUM_RUNS-1];
    reg [23:0]      expected_conv2 [0:CONV2_WORDS-1];
    reg [8*128-1:0] input_file;

    integer run;
    integer pred_errors  = 0;
    integer conv2_errors = 0;

    // stored Conv2 word for output channel ch at address a (row * 24 + col)
    function [23:0] conv2_word(input integer ch, input integer a);
        begin
            case (ch)
                0:       conv2_word = dut.gen_conv2_result[0].u_sram_conv2_result.mem[a];
                1:       conv2_word = dut.gen_conv2_result[1].u_sram_conv2_result.mem[a];
                2:       conv2_word = dut.gen_conv2_result[2].u_sram_conv2_result.mem[a];
                3:       conv2_word = dut.gen_conv2_result[3].u_sram_conv2_result.mem[a];
                4:       conv2_word = dut.gen_conv2_result[4].u_sram_conv2_result.mem[a];
                5:       conv2_word = dut.gen_conv2_result[5].u_sram_conv2_result.mem[a];
                6:       conv2_word = dut.gen_conv2_result[6].u_sram_conv2_result.mem[a];
                7:       conv2_word = dut.gen_conv2_result[7].u_sram_conv2_result.mem[a];
                8:       conv2_word = dut.gen_conv2_result[8].u_sram_conv2_result.mem[a];
                9:       conv2_word = dut.gen_conv2_result[9].u_sram_conv2_result.mem[a];
                10:      conv2_word = dut.gen_conv2_result[10].u_sram_conv2_result.mem[a];
                11:      conv2_word = dut.gen_conv2_result[11].u_sram_conv2_result.mem[a];
                12:      conv2_word = dut.gen_conv2_result[12].u_sram_conv2_result.mem[a];
                13:      conv2_word = dut.gen_conv2_result[13].u_sram_conv2_result.mem[a];
                14:      conv2_word = dut.gen_conv2_result[14].u_sram_conv2_result.mem[a];
                default: conv2_word = dut.gen_conv2_result[15].u_sram_conv2_result.mem[a];
            endcase
        end
    endfunction

    task check_conv2;
        integer ch, a;
        begin
            for (ch = 0; ch < 16; ch = ch + 1)
                for (a = 0; a < 576; a = a + 1)
                    if (conv2_word(ch, a) !== expected_conv2[ch*576 + a]) begin
                        if (conv2_errors < 5)
                            $display("MISMATCH Conv2 ch %0d addr %0d: got %06h, expected %06h",
                                     ch, a, conv2_word(ch, a), expected_conv2[ch*576 + a]);
                        conv2_errors = conv2_errors + 1;
                    end
            $display("Conv2 result memories after run 0: %0d of %0d words match",
                     CONV2_WORDS - conv2_errors, CONV2_WORDS);
        end
    endtask

    task check_prediction(input integer image, input [3:0] got);
        begin
            if (got !== expected[image]) begin
                pred_errors = pred_errors + 1;
                $display("MISMATCH image %0d: got %0d, expected %0d", image, got, expected[image]);
            end
        end
    endtask

    initial begin
        $readmemh({`VECTOR_DIR, "/conv_weight_flatten.hex"}, conv_mem);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_0.hex"}, fc_mem_0);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_1.hex"}, fc_mem_1);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_2.hex"}, fc_mem_2);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_3.hex"}, fc_mem_3);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_4.hex"}, fc_mem_4);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_5.hex"}, fc_mem_5);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_6.hex"}, fc_mem_6);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_7.hex"}, fc_mem_7);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_8.hex"}, fc_mem_8);
        $readmemh({`VECTOR_DIR, "/fc1_weight_flatten_9.hex"}, fc_mem_9);
        $readmemh({`VECTOR_DIR, "/expected_predictions.hex"}, expected);
        $readmemh({`VECTOR_DIR, "/expected_conv2_run0.hex"}, expected_conv2);

        #20 resetn = 1'b1;

        for (run = 0; run < NUM_RUNS; run = run + 1) begin
            $sformat(input_file, "%0s/input_run%0d_flatten.hex", `VECTOR_DIR, run);
            $readmemh(input_file, input_mem);
            // start is driven on falling edges: done rises on a rising edge, so a fixed delay after
            // it would change start exactly when the controller samples it
            repeat (20) @(negedge clk);
            start = 1'b1;
            @(negedge clk);
            start = 1'b0;

            wait (done);
            #200;
            $display("Run %0d (images %0d-%0d): predicted %0d %0d %0d",
                     run, 3*run, 3*run + 2, result_0, result_1, result_2);
            check_prediction(3*run,     result_0);
            check_prediction(3*run + 1, result_1);
            check_prediction(3*run + 2, result_2);
            if (run == 0)
                check_conv2;
        end

        if (pred_errors == 0 && conv2_errors == 0)
            $display("PASS: CNN predictions match the golden model (%0d images, %0d Conv2 words)",
                     3*NUM_RUNS, CONV2_WORDS);
        else
            $display("FAIL: %0d of %0d predictions and %0d of %0d Conv2 words differ",
                     pred_errors, 3*NUM_RUNS, conv2_errors, CONV2_WORDS);
        $finish;
    end

endmodule
