`timescale 1ns / 1ps

// Testbench for the SRAM packing controller. SRAM1 is loaded from vectors/init_memory.hex, the
// controller is reset and started, and once done rises every one of the 192 words in SRAM2 is
// compared with vectors/answer_memory.hex (both generated by tools/gen_vectors.py).
//
// VECTOR_DIR is resolved against the simulator's working directory; tools/run_sims.py copies
// vectors/ there. Override it with -d VECTOR_DIR=<path> if needed.
`ifndef VECTOR_DIR
  `define VECTOR_DIR "vectors"
`endif

module tb_memory_ctrlr;

    reg clk = 1'b0;
    always #5 clk <= ~clk;

    reg  resetn;
    reg  start;
    wire done;

    reg [31:0] expected [0:191];

    integer i;

    top_memory_ctrlr dut (
        .clk(clk),
        .resetn(resetn),
        .start(start),
        .done(done)
    );

    task compare_memory;
        begin
            $readmemh({`VECTOR_DIR, "/answer_memory.hex"}, expected);
            for (i = 0; i < 192; i = i + 1) begin
                if (dut.u_sram2.mem[i] !== expected[i]) begin
                    $display("FAIL: memory comparison failed at %0t ns", $time);
                    $display("    word %0d: expected %h, got %h",
                             i, expected[i], dut.u_sram2.mem[i]);
                    $writememh("result_memory.hex", dut.u_sram2.mem);
                    $finish;
                end
                if (i < 10)
                    $display("word %0d: expected %h, got %h", i, expected[i], dut.u_sram2.mem[i]);
            end
            $display("PASS: memory comparison succeeded at %0t ns", $time);
            $writememh("result_memory.hex", dut.u_sram2.mem);
        end
    endtask

    initial begin
        $readmemh({`VECTOR_DIR, "/init_memory.hex"}, dut.u_sram1.mem);
    end

    initial begin
        resetn <= 1'b1;
        start  <= 1'b0;

        #302 resetn <= 1'b0;
        #50  resetn <= 1'b1;
        #50  start  <= 1'b1;
        #10  start  <= 1'b0;

        @(posedge done) begin
            #10 compare_memory;
            #10 $finish;
        end
    end

    // safety net in case done never rises
    initial begin
        #300_000;
        $display("FAIL: timed out waiting for done at %0t ns", $time);
        $finish;
    end

endmodule
